---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-gnbsim
  labels:
    app: free5gc-gnbsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-gnbsim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-gnbsim
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-gnbsim-n1n2n3
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: free5gc-gnbsim
          image: black842679513/free5gc-gnbsim:v3.0.5
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          command: ["sh"]
          tty: true
          securityContext:
            # allow container to access the host's resources
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
          volumeMounts:
            - name: free5gc-gnbsim-config
              mountPath: /gnbsim/config
              # read host linux tun/tap packets
            - name: tun-dev-dir  
              mountPath: /dev/net/tun
          ports:
            - containerPort: 38412
              name: if-n1n2
              protocol: SCTP
            - containerPort: 2152
              name: if-n3
              protocol: UDP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: free5gc-gnbsim-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: free5gc-gnbsim-config
          configMap:
            name: free5gc-gnbsim-config
        - name: tun-dev-dir
          hostPath:
            path: /dev/net/tun
