---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-gnbsim
  name: free5gc-gnbsim
spec:
  type: ClusterIP
  ports:
  - name: free5gc-gnbsim-n1n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
  - name: free5gc-gnbsim-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: free5gc-gnbsim
