---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - gnbsim-sa.yaml
  - gnbsim-rbac.yaml
  - gnbsim-multus.yaml
  - gnbsim-service.yaml
  - gnbsim-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-gnbsim-config
  namespace: free5gc
  files:
    - config/example.json
