---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upf-2
  labels:
    app: free5gc-upf-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-upf-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-upf-2
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-upf-2-n3, free5gc-upf-2-n4, free5gc-upf-2-n6
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: free5gc-upf-2
          image: black842679513/free5gc-upf:v3.0.5
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
            # add network capabilities
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE", "SYS_TIME"]
          volumeMounts:
            - name: free5gc-upf-2-config
              mountPath: /free5gc/config
              # read host linux tun/tap packets
            - name: tun-dev-dir
              mountPath: /dev/net/tun
          ports:
            - containerPort: 2152
              name: if-n3
              protocol: UDP
            - containerPort: 8805
              name: if-n4
              protocol: UDP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: free5gc-upf-2-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: free5gc-upf-2-config
          configMap:
            name: free5gc-upf-2-config
        - name: tun-dev-dir
          hostPath:
            path: /dev/net/tun
