---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- node-affinity.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-gnbsim-config
  namespace: free5gc
  behavior: replace
  files:
    - config/example.json
