---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: free5gc-gnbsim
  name: free5gc-gnbsim
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - worker-gnb
