---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - ueransim-ue-sa.yaml
  - ueransim-ue-rbac.yaml
  - ueransim-ue-multus.yaml
  - ueransim-ue-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-ueransim-ue-config
  namespace: free5gc
  files:
    - config/custom-gnb.yaml
    - config/custom-ue.yaml
    - config/free5gc-gnb.yaml
    - config/free5gc-ue.yaml
    - config/open5gs-gnb.yaml
    - config/open5gs-ue.yaml
