---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - ueransim-gnb-sa.yaml
  - ueransim-gnb-rbac.yaml
  - ueransim-gnb-multus.yaml
  - ueransim-gnb-service.yaml
  - ueransim-gnb-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-ueransim-gnb-config
  namespace: free5gc
  files:
    - config/custom-gnb.yaml
    - config/custom-ue.yaml
    - config/free5gc-gnb.yaml
    - config/free5gc-ue.yaml
    - config/open5gs-gnb.yaml
    - config/open5gs-ue.yaml
