---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: free5gc-upf-1
  name: free5gc-upf-1
  annotations:
    ns.networkservicemesh.io: secure-intranet-connectivity
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "vpn-gateway-nsc"
      networkservicemesh.io/impl: "secure-intranet-connectivity"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "vpn-gateway-nsc"
        networkservicemesh.io/impl: "secure-intranet-connectivity"
    spec:
      serviceAccountName: nsc-acc
